In [27]:
# to keep record of product, quantity, total price

j =0
sm=0
info = ""
n = int (input("enter no product"))

while j<n:
    p = input("enter product")
    c =int( input ("enter quantity"))
    f = int(input ("enter price"))
    sm = sm+c*f
    info = info + f"{p},{c},{f}, {sm}\n"
    j = j+1
file = open("bill.csv",'w' )
file.write("name,price, quantity, total \n")
file.write(info)
file.close()

In [30]:
try:
    file = open('info.csv','x' )
    file.close()

except:
    print("the file is already there")

the file is already there

In [43]:
import pandas as pd
df= pd.read_csv('info.csv')
df

      name   quantity  price   total
0   banana          2     33       66
1    apple          2     22      110
2  banana1          2     33       66
3   apple6          2     22      110
4  banana2          2     33       66
5   apple5          2     22      110
6  banana3          2     33       66
7   apple4          2     22      110

In [44]:
df.head(8) # get first 8 
# df.tail(3)
# df.iloc[1:4]

      name   quantity  price   total
0   banana          2     33       66
1    apple          2     22      110
2  banana1          2     33       66
3   apple6          2     22      110
4  banana2          2     33       66
5   apple5          2     22      110
6  banana3          2     33       66
7   apple4          2     22      110

In [45]:
df.loc[1:4]

      name   quantity  price   total
1    apple          2     22      110
2  banana1          2     33       66
3   apple6          2     22      110
4  banana2          2     33       66

In [50]:
df[df['price']>=22]

      name   quantity  price   total
0   banana          2     33       66
1    apple          2     22      110
2  banana1          2     33       66
3   apple6          2     22      110
4  banana2          2     33       66
5   apple5          2     22      110
6  banana3          2     33       66
7   apple4          2     22      110